"use client"


function page() {
	const names = [
		'Emma',
		'Noah',
		'Olivia',
		'Liam',
		'Ava',
		'Sophia',
		'Isabella',
		'Mia',
		'Charlotte',
		'Amelia',
		'Harper',
		'Evelyn',
		'Abigail',
		'Emily',
		'Elizabeth',
		'Mila',
		'Ella',
		'Avery',
		'Sofia',
		'Camila',
		'Aria',
		'Scarlett',
		'Victoria',
		'Madison',
		'Luna',
		'Grace',
		'Chloe',
		'Penelope',
		'Layla',
		'Riley',
		'Zoey',
		'Nora',
		'Lily',
		'Eleanor',
		'Hannah',
		'Lillian',
		'Addison',
		'Aubrey',
		'Ellie',
		'Stella',
		'Natalie',
		'Zoe',
		'Leah',
		'Hazel',
		'Violet',
		'Aurora',
		'Savannah',
		'Audrey',
		'Brooklyn',
		'Bella',
		'Claire',
		'Skylar',
		'Lucy',
		'Paisley',
		'Everly',
		'Anna',
		'Caroline',
		'Nova',
		'Genesis',
		'Emilia',
		'Kennedy',
		'Samantha',
		'Maya',
		'Willow',
		'Kinsley',
		'Naomi',
		'Aaliyah',
		'Elena',
		'Sarah',
		'Ariana',
		'Allison',
		'Gabriella',
		'Alice',
		'Madelyn',
		'Cora',
		'Ruby',
		'Eva',
		'Serenity',
		'Autumn',
		'Adeline',
		'Hailey',
		'Gianna',
		'Valentina',
		'Isla',
		'Eliana',
		'Quinn',
		'Nevaeh',
		'Ivy',
		'Sadie',
		'Piper',
		'Lydia',
		'Alexa',
		'Josephine',
		'Emery',
		'Julia',
		'Delilah',
		'Arianna',
		'Vivian',
		'Kaylee',
		'Sophie',
	];

	const usernames = [
		'user123',
		'jsmith',
		'jdoe',
		'alice123',
		'bobby',
		'emma_w',
		'michaelm',
		'olivia12',
		'willw',
		'sophie',
		'emma1',
		'noah2',
		'olivia3',
		'liam4',
		'ava5',
		'sophia6',
		'isabella7',
		'mia8',
		'charlotte9',
		'amelia10',
		'harper11',
		'evelyn12',
		'abigail13',
		'emily14',
		'elizabeth15',
		'mila16',
		'ella17',
		'avery18',
		'sofia19',
		'camila20',
		'aria21',
		'scarlett22',
		'victoria23',
		'madison24',
		'luna25',
		'grace26',
		'chloe27',
		'penelope28',
		'layla29',
		'riley30',
		'zoey31',
		'nora32',
		'lily33',
		'eleanor34',
		'hannah35',
		'lillian36',
		'addison37',
		'aubrey38',
		'ellie39',
		'stella40',
		'natalie41',
		'zoe42',
		'leah43',
		'hazel44',
		'violet45',
		'aurora46',
		'savannah47',
		'audrey48',
		'brooklyn49',
		'bella50',
		'claire51',
		'skylar52',
		'lucy53',
		'paisley54',
		'everly55',
		'anna56',
		'caroline57',
		'nova58',
		'genesis59',
		'emilia60',
		'kennedy61',
		'samantha62',
		'maya63',
		'willow64',
		'kinsley65',
		'naomi66',
		'aaliyah67',
		'elena68',
		'sarah69',
		'ariana70',
		'allison71',
		'gabriella72',
		'alice73',
		'madelyn74',
		'cora75',
		'ruby76',
		'eva77',
		'serenity78',
		'autumn79',
		'adeline80',
		'hailey81',
		'gianna82',
		'valentina83',
		'isla84',
		'eliana85',
		'quinn86',
		'nevaeh87',
		'ivy88',
		'sadie89',
		'piper90',
		'lydia91',
		'alexa92',
		'josephine93',
		'emery94',
		'julia95',
		'delilah96',
		'arianna97',
		'vivian98',
		'kaylee99',
		'sophie100',
	];

	const generateRandomData = (index) => {
		const randomInt = (min, max) =>
			Math.floor(Math.random() * (max - min + 1) + min);

		const ExamStatusData = {
			ExamID: 'lirfquhz',
			userName: usernames[index % usernames.length],
			Name: names[index % names.length],
			ExitFullScreen: randomInt(0, 100),
			TabChange: randomInt(0, 100),
			NoOfTimeLookedOut: randomInt(0, 100),
			LeftPlace: randomInt(0, 100),
			OtherPerson: randomInt(0, 100),
			CellPhoneDetected: randomInt(0, 100),
			LaptopDetected: randomInt(0, 100),
			BookDetected: randomInt(0, 100),
			Latitude: (Math.random() * 180 - 90).toFixed(6),
			Longitude: (Math.random() * 360 - 180).toFixed(6),
			FinishedExam: Math.random() < 0.5,
			Rating: randomInt(0, 100),
			Like: Math.random() < 0.5,
		};

		return ExamStatusData;
	};

	// useEffect(() => {
	// 	const dataArray = Array.from({ length: 100 }, (_, index) =>
	// 		generateRandomData(index)
	// 	);
	// 	for (let index = 0; index < 100; index++) {
	// 		createExamStatus(generateRandomData(index));
	// 	}
	// }, []);

	// deleteExamStatusDocuments();

	//   console.log(dataArray);

	return <div>page</div>;
}

export default page;
